FIG = suppFigs/powerLaw/res-raw10kb.pdf \
      suppFigs/powerLaw/res-ICE10kb.pdf \
      suppFigs/ICEbiasPlots/REsite/TROPHOZOITES-XL-before.pdf \
      suppFigs/ICEbiasPlots/REsite/TROPHOZOITES-XL-after.pdf \
      suppFigs/ICEbiasPlots/GCcontent/TROPHOZOITES-XL-before.pdf \
      suppFigs/ICEbiasPlots/GCcontent/TROPHOZOITES-XL-after.pdf \
      suppFigs/ICEbiasPlots/Mappability/TROPHOZOITES-XL-before.pdf \
      suppFigs/ICEbiasPlots/Mappability/TROPHOZOITES-XL-after.pdf \
      suppFigs/ICEbiasPlots/REsite/SCHIZONTS-before.pdf \
      suppFigs/ICEbiasPlots/REsite/SCHIZONTS-after.pdf \
      suppFigs/ICEbiasPlots/GCcontent/SCHIZONTS-before.pdf \
      suppFigs/ICEbiasPlots/GCcontent/SCHIZONTS-after.pdf \
      suppFigs/ICEbiasPlots/Mappability/SCHIZONTS-before.pdf \
      suppFigs/ICEbiasPlots/Mappability/SCHIZONTS-after.pdf \
      suppFigs/ICEbiasPlots/REsite/RINGS-before.pdf \
      suppFigs/ICEbiasPlots/REsite/RINGS-after.pdf \
      suppFigs/ICEbiasPlots/GCcontent/RINGS-before.pdf \
      suppFigs/ICEbiasPlots/GCcontent/RINGS-after.pdf \
      suppFigs/ICEbiasPlots/Mappability/RINGS-before.pdf \
      suppFigs/ICEbiasPlots/Mappability/RINGS-after.pdf \
      suppFigs/perChrPages/chr1-lowRes.pdf \
      suppFigs/perChrPages/chr2-lowRes.pdf \
      suppFigs/perChrPages/chr3-lowRes.pdf \
      suppFigs/perChrPages/chr4-lowRes.pdf \
      suppFigs/perChrPages/chr5-lowRes.pdf \
      suppFigs/perChrPages/chr6-lowRes.pdf \
      suppFigs/perChrPages/chr7-lowRes.pdf \
      suppFigs/perChrPages/chr8-lowRes.pdf \
      suppFigs/perChrPages/chr9-lowRes.pdf \
      suppFigs/perChrPages/chr10-lowRes.pdf \
      suppFigs/perChrPages/chr11-lowRes.pdf \
      suppFigs/perChrPages/chr12-lowRes.pdf \
      suppFigs/perChrPages/chr13-lowRes.pdf \
      suppFigs/perChrPages/chr14-lowRes.pdf \
      suppFigs/stabilityOf3Dinference/compareStructurePairs.png \
      suppFigs/stabilityOf3Dinference/allStages-clustering.png \
      suppFigs/3Dall/all3D-centromeres-angle-lowRes.png \
      suppFigs/clusteringComparmentDists/RINGS.pdf \
      suppFigs/clusteringComparmentDists/RINGS-hierCluster-dists.pdf \
      suppFigs/clusteringComparmentDists/TROPHOZOITES-XL.pdf \
      suppFigs/clusteringComparmentDists/TROPHOZOITES-XL-hierCluster-dists.pdf \
      suppFigs/clusteringComparmentDists/SCHIZONTS.pdf \
      suppFigs/clusteringComparmentDists/SCHIZONTS-hierCluster-dists.pdf \
      suppFigs/FISH/varPair.png \
      suppFigs/FISH/nonvarPair.png \
      suppFigs/FISH/controlPair.png \
      suppFigs/Newbold-virtual4Cs/DCJ_On-HiC-MboI/chr7-rDNA/chr5.pdf \
      suppFigs/Newbold-virtual4Cs/DCJ_Off-HiC-MboI/chr7-rDNA/chr5.pdf \
      suppFigs/Newbold-virtual4Cs/B15C2-HiC-MboI/chr7-rDNA/chr5.pdf \
      suppFigs/Newbold-virtual4Cs/NF54-Control-MboI/chr7-rDNA/chr5.pdf \
      suppFigs/clusteringComparmentDists/RINGS.pdf \
      suppFigs/clusteringComparmentDists/RINGS-hierCluster-dists.pdf \
      suppFigs/intraVSinter/per10kb-B15C2-HiC-MboI.pdf \
      suppFigs/intraVSinter/equalOcc-B15C2-HiC-MboI.pdf \
      suppFigs/intraVSinter/equalOcc-RINGS.pdf \
      suppFigs/intraVSinter/equalOcc-TROPHOZOITES-XL.pdf \
      suppFigs/intraVSinter/equalOcc-SCHIZONTS.pdf \
      suppFigs/chrTerritory/diam2point5.pdf \
      suppFigs/clusteringComparmentDists/RINGS-minus-TROPHOZOITES-XL.pdf \
      suppFigs/clusteringComparmentDists/TROPHOZOITES-XL-minus-SCHIZONTS.pdf \
      suppFigs/VE/correlation-per-num-experiments.pdf \
      suppFigs/TADs/TAD-descriptive.png \
      suppFigs/VE/correlation-per-num-experiments.png \
      suppFigs/expVSdists/all-corr-contactCounts.pdf \
      suppFigs/expVSdists/all-corr-contactCounts-withoutVRSM.pdf \
      suppFigs/expVSdists/all-100-3Ddists.pdf \
      suppFigs/expVSdists/all-100-3Ddists-withoutVRSM.pdf \
      suppFigs/expVSdists/telomeres-100-corr.pdf \
      suppFigs/expVSdists/telomeres-100-corr-withoutVRSM.pdf \
      suppFigs/expVSdists/centromeres-100-corr.pdf \
      suppFigs/expVSdists/center-100-corr.pdf \
      suppFigs/kCCA/RINGS-kcca-genes-1.png  \
      suppFigs/kCCA/RINGS-kcca-genes-2.png \
      suppFigs/kCCA/TROPH-kcca-genes-1.png \
      suppFigs/kCCA/TROPH-kcca-genes-2.png \
      suppFigs/kCCA/SCHIZONTS-kcca-genes-1.png \
      suppFigs/kCCA/SCHIZONTS-kcca-genes-2.png \
      suppFigs/kCCA/legend.png \
      suppFigs/3Dclustering/RINGS.pdf \
      suppFigs/3Dclustering/TROPHOZOITES.pdf \
      suppFigs/3Dclustering/SCHIZONTS.pdf


all: prepare $(FIG)

prepare:
	mkdir -p suppFigs/powerLaw
	mkdir -p suppFigs/ICEbiasPlots/REsite
	mkdir -p suppFigs/ICEbiasPlots/GCcontent
	mkdir -p suppFigs/ICEbiasPlots/Mappability
	mkdir -p suppFigs/perChrPages/
	mkdir -p suppFigs/stabilityOf3Dinference
	mkdir -p suppFigs/3Dall
	mkdir -p suppFigs/clusteringComparmentDists
	mkdir -p suppFigs/FISH
	mkdir -p suppFigs/Newbold-virtual4Cs/DCJ_On-HiC-MboI/chr7-rDNA
	mkdir -p suppFigs/Newbold-virtual4Cs/DCJ_Off-HiC-MboI/chr7-rDNA
	mkdir -p suppFigs/Newbold-virtual4Cs/B15C2-HiC-MboI/chr7-rDNA
	mkdir -p suppFigs/Newbold-virtual4Cs/NF54-Control-MboI/chr7-rDNA
	mkdir -p suppFigs/clusteringComparmentDists
	mkdir -p suppFigs/intraVSinter
	mkdir -p suppFigs/chrTerritory
	mkdir -p suppFigs/VE
	mkdir -p suppFigs/kCCA
	mkdir -p suppFigs/TADs
	mkdir -p suppFigs/expVSdists
	mkdir -p suppFigs/3Dclustering

suppFigs/%:
	mkdir -p suppFigs
	wget http://cbio.ensmp.fr/~nvaroquaux/phd_manuscript/8_plasmodium_supplementaries/$@ -O $@

clean:
	rm -rf suppFigs
